### ISSUE TITLE
Use ruby-lang.org design, if possible?

### ISSUE THREAD

**Issue by prognostikos** [copenhagenrb/copenhagenrb.github.io#4]
ruby-lang.org is also an open-source Jekyll site, at https://github.com/ruby/www.ruby-lang.org/

It has a bit more modern look and feel, IMHO.

What do people think about the idea of using that design, if permitted?

**Comment by jamiehodge** [comment]
See https://github.com/copenhagenrb/copenhagenrb.github.io/pull/15
